### ISSUE TITLE
Units display whether I select metric or US customary

### ISSUE THREAD

**Issue by alcar2364** [Cities2Modding/LegacyFlavour#1]
So, I love the mod, but prefer my measurements in meters instead of units. I kept the selection on metric, but it still displays units when I'm building a road. Switching to US customary and back to metric doesn't fix. Don't know if it is intended to be this way or not.

**Comment by users112023** [comment]
I have the same problem too...
It would be nice to have all 3 possibilities usable

imperial, metric, points.
Thank you

**Comment by optimus-code** [comment]
The new update has introduced a toggle for units. Please see the README or release notes :)
