### ISSUE TITLE
Game Crashs on load

### ISSUE THREAD

**Issue by cmill1023** [Cities2Modding/LegacyFlavour#10]
once I downloaded the file in my plugins folder it started crashing the game. I uninstalled this mod and it worked just fine again with my other mods.

**Comment by qualiall** [comment]
Crashed for me too, but it was when I clicked on the in game icon thingie and the Legacy Flavour option -hard crash to desktop.  This is my log output, but it doesn't mention Legacy in it so not sure if it helps.
[LogOutput.log](https://github.com/Cities2Modding/LegacyFlavour/files/13652203/LogOutput.log)

**Comment by optimus-code** [comment]
> Crashed for me too, but it was when I clicked on the in game icon thingie and the Legacy Flavour option -hard crash to desktop. This is my log output, but it doesn't mention Legacy in it so not sure if it helps. [LogOutput.log](https://github.com/Cities2Modding/LegacyFlavour/files/13652203/LogOutput.log)

Looking at the LogOutput LegacyFlavour is not even loading. If you are having the UI option still presented then it's a HookUI issue probably related to cache of the Javascript.

@cmill1023 Can you provide the LogOutput ? Also is this a fresh install? Do you have HookUI installed?

**Comment by optimus-code** [comment]
This issue has been identified should now be resolved
