### ISSUE TITLE
Remove Gooee Dependency

### ISSUE THREAD

**Issue by vinceingithub** [Cities2Modding/LegacyFlavour#24]
This mod relies on Gooee which is now deprecated and incompatible with popular mods such as Traffic Light Enhancer and Road Builder. As it stands now, you cannot use Legacy Flavor, Traffic Light Enhancer, and Road Builder in one mod list which is a shame. Please consider re-working this mod to not have this dependency.

**Comment by optimus-code** [comment]
None of Cities2Modding mods are actively supported unless other people have taken them on. Gooee is not deprecated it's just not updated, same as Legacy Flavour.
