### ISSUE TITLE
BUG - All views are not showing

### ISSUE THREAD

**Issue by Micle-1999** [Cities2Modding/LegacyFlavour#6]
With this mod installed via Thunderstore Mod Manager I can't see any specific view (like School view, population view, etc...).

Note: I installed ONLY this mod so I'm pretty sure there is no conflicts caused by other mods.

With mod:
![image](https://github.com/Cities2Modding/LegacyFlavour/assets/59797135/9d16fb6a-b4c3-4fb6-8847-4c628f3fa1d9)
![image](https://github.com/Cities2Modding/LegacyFlavour/assets/59797135/dfdab468-303c-4969-8163-db453721ac37)

With the mod disabled:
![image](https://github.com/Cities2Modding/LegacyFlavour/assets/59797135/68e91ff3-5cb6-4b76-8dce-5cff7232074e)
![image](https://github.com/Cities2Modding/LegacyFlavour/assets/59797135/f550c35c-ad33-4daa-8d02-994b1d196c66)

**Comment by JoepWi** [comment]
I have the same issue and disabling the mod solved the problem. So it's for sure the mod causing it.

**Comment by optimus-code** [comment]
This is a feature. The new update includes a "sticky" whiteness toggle that defaults to on. Please see the README or update notes on the release to see the shortcuts to control this behaviour.

**Comment by optimus-code** [comment]
This is a feature. The new update includes a "sticky" whiteness toggle that defaults to on. Please see the README or update notes on the release to see the shortcuts to control this behaviour.

**Comment by JoepWi** [comment]
That control does not work for me.
